services:
  mysql:
    image: mysql:8.4
    container_name: graduation_project_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: graduation_project
      MYSQL_USER: app
      MYSQL_PASSWORD: app_password
      MYSQL_ROOT_PASSWORD: root_password
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_0900_ai_ci
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

